# Generated by Django 5.2.17 on 2026-08-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image_thumbnail_alter_image_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
